### PR TITLE
Refactor fullscreen button to use NgxScreenfull, add back to bottom bar

### PR DESCRIPTION
**Pull request by floogulinc**
Removes our old fullscreen button logic and replaces it with the [@ngx-extensions/screenful](https://www.npmjs.com/package/@ngx-extensions/screenfull) library. Also adds the fullscreen button back to the bottom bar replacing the menu button that wasn't being used.

### CODE REVIEW

**Review by UtkarshKr007 — DISMISSED** [review]
I really like the big display in full screen mode. Great addition. We also provide a cancel button or a back button on every page that can be full screen, so the loss of browser's back button doesn't affect any sort of navigation.

**Comment by floogulinc** [comment]
> I really like the big display in full screen mode. Great addition. We also provide a cancel button or a back button on every page that can be full screen, so the loss of browser's back button doesn't affect any sort of navigation.

I made it so quitting the session leaves fullscreen so we really only intend the session lobby and onward to be fullscreen and don't have to worry about providing a fullscreen button anywhere else.

**Comment by floogulinc** [comment]
Looks like there is a bug when you start a round while being fullscreen the button icon reset.

**Review by UtkarshKr007 — APPROVED** [review]
The full screen icon reseting bug is fixed and everything else looks great just as before.

**Review by kklamberty — APPROVED** [review]
This looks great to me! I tried out a bunch of different things to try to break it and it seems pretty robust. Nice work!

**Pull request merged**
