### PR TITLE
Add GH Actions workflow for unit tests

### PR DESCRIPTION
**Pull request by floogulinc**

### CODE REVIEW

**Comment by floogulinc** [comment]
We won't be testing everything but there is a lot of modular logic stuff that we can do unit testing for.

**Comment by helloworld12321** [comment]
Am I remembering correctly that we're waiting to update the tests until after the Timer refactoring has gone through?

**Comment by floogulinc** [comment]
There are probably many components we simply won't test (like the AR one) but we have some tests for our new timer stuff so it would be nice to have the GH Actions workflow for that.

**Comment by floogulinc** [comment]
Once this is merged I will be pulling it into the timer branch so we can have it running those tests.

**Pull request merged**
