### PR TITLE
Update @mn-pollinators/assets to v0.4.0

### PR DESCRIPTION
**Pull request by floogulinc**
https://buzz-about-git-assets-v040.mn-pollinators.vercel.app/test/json-data-test

### CODE REVIEW

**Comment by helloworld12321** [comment]
Okay, that's really cool.
image

**Review by helloworld12321 — APPROVED** [review]
Looks wonderful—thanks, Paul!

I know you were concerned about how the bumblebee nest looks in AR, but I think it shows up just fine:

Screenshot_2020-12-17 Buzz About

**Comment by helloworld12321** [comment]
@floogulinc Also, do we want to add the new scientific names to the spell-checker? (If so, I made a little patch file that does that! :-) [cspell-additions.patch.txt](https://github.com/mn-pollinators/buzz-about/files/5712473/cspell-additions.patch.txt))

**Comment by floogulinc** [comment]
> @floogulinc Also, do we want to add the new scientific names to the spell-checker? (If so, I made a little patch file that does that! :-) [cspell-additions.diff.txt](https://github.com/mn-pollinators/buzz-about/files/5712486/cspell-additions.diff.txt))

Good idea, can you go ahead and commit that?

**Review by helloworld12321 — APPROVED** [review]

**Review by UtkarshKr007 — APPROVED** [review]
Confirmed with wikipedia all scientific names are spelled right. Looks great.

**Pull request merged**
