### PR TITLE
Add fix for field guide images in Webkit

### PR DESCRIPTION
**Pull request by floogulinc**
This is a (hopefully temporary) fix for the issue we were having where images wouldn't display in the field guide dialog in Webkit (Safari). We now replace the images in the field guide dialog with the 512 square versions only on Webkit so we can set a default width/height for those.

### CODE REVIEW

**Review by kklamberty — APPROVED** [review]
I think this fixes the problem; I always had an image. On my iPhone, I noticed that when I close the dialog about an individual field guide element there is a flash like things are loading twice. This doesn't happen in Safari on my desktop, and it doesn't see to happen with the elements that show before I scroll (those first 4 flowers). Does that relate directly to part of the fix or is it something to try to capture and look into?

**Review by audreylemeur — COMMENTED** [review]
The photos all load but they look very squished on my iPhone SE.
image

**Comment by floogulinc** [comment]
> The photos all load but they look very squished on my iPhone SE.

@audreylemeur This only happens on iOS 10, which we don't support.

**Review by helloworld12321 — APPROVED** [review]
(Approving, even though I worked on this PR, because not many people in this project have devices on which to test this fix.)

**Pull request merged**
