### PR TITLE
Add card to about page when an update is available

### LINKED ISSUE #43: Add service worker update notifications

### PR DESCRIPTION
**Pull request by floogulinc**
Also adds a hidden way to force it to check for updates by clicking or tapping the version subtitle in the Buzz About card.

Closes #43 

image

### CODE REVIEW

**Review by kklamberty — COMMENTED** [review]
Can you help me figure out a good way to see this functionality in action? Thanks!

**Comment by floogulinc** [comment]
> Can you help me figure out a good way to see this functionality in action? Thanks!

There really isn't a good way to test this yourself. The update notification will only appear when there is a new version of the app on the server.

**Review by helloworld12321 — APPROVED** [review]
Works like a charm—thanks, Paul! :)

**Comment by helloworld12321** [comment]
@kklamberty, I found a guide from the Angular folks about how to test service workers locally—these are the steps I was following:

https://angular.io/guide/service-worker-getting-started#service-worker-in-action-a-tour

It's a bit of a complicated process, but you should be able to see the update notifications work 🙂

**Comment by floogulinc** [comment]
> @kklamberty, I found a guide from the Angular folks about how to test service workers locally—these are the steps I was following:
> 
> https://angular.io/guide/service-worker-getting-started#service-worker-in-action-a-tour
> 
> It's a bit of a complicated process, but you should be able to see the update notifications work 🙂

Good find. It should be noted that there is a flag to make `ng serve` use https.

**Review by helloworld12321 — APPROVED** [review]

**Review by kklamberty — APPROVED** [review]

**Comment by kklamberty** [comment]
I checked again after approving this, and noticed that the GitHub icons were not appearing for me on that deployment. Is that true for everyone? @floogulinc @helloworld12321

**Comment by helloworld12321** [comment]
@kklamberty I have that problem too—I get the following error in the console:

`Error: Error retrieving icon :github! <svg> tag not found`

**Comment by helloworld12321** [comment]
Looks like it's just the Vercel build, for some reason—<buzzabout.app> is fine.

**Comment by helloworld12321** [comment]
Yep, okay, it looks like these lines in `about.component.ts` are the problem:

```ts
  constructor(iconRegistry: MatIconRegistry, sanitizer: DomSanitizer, public updates: SwUpdate) {
    iconRegistry.addSvgIcon(
      'github',
      sanitizer.bypassSecurityTrustResourceUrl('assets/github.svg')
    );
  }
```

The constructor is still trying to load the SVG icon from assets, even though it doesn't live there anymore. (It's actually shadowing the correct version of the icon with the broken version.)

I'll make a quick PR to fix that.

Sorry—my fault for re-approving the changes without looking at the deployment :(

**Comment by helloworld12321** [comment]
Okay, PR #216 should fix that issue :) Thanks for spotting it @kklamberty!

**Pull request merged**
