### PR TITLE
Set up secure Firestore rules and testing for rules

### LINKED ISSUE #102: Set up secure Firestore rules and testing for rules

### PR DESCRIPTION
**Pull request by floogulinc**
Closes #102

### CODE REVIEW

**Review by kklamberty — APPROVED** [review]
This looks great to me!

**Comment by audreylemeur** [comment]
How would I try this out?

**Comment by helloworld12321** [comment]
Oh, I wonder if you could use the rules-tester-thingy in the Firebase console? I don't use it very often, so I'm not sure if it's exactly what you want, but that might help!

**Comment by floogulinc** [comment]
> How would I try this out?

You should probably run the tests on your own machine as well as running the app itself locally to see if anything is broken from the new rules.

**Review by audreylemeur — APPROVED** [review]

**Pull request merged**
