### PR TITLE
Bug fixes and refactoring in the AR View component

### PR DESCRIPTION
**Pull request by floogulinc**
This PR cleans up and attempts to fix some bugs in the AR View component. Testing for all of these things is fairly difficult so it would be great to test this on real devices to see if some of the issues we noticed in play testing are gone.

Specifically, we hope to have fixed:
- The issues with just getting a white screen sometimes instead of the AR view
- AR view just totally freezing on Android

This PR also removes the old debug view for AR which we haven't used in a while.

### CODE REVIEW

**Comment by helloworld12321** [comment]
(I probably shouldn't review this given that I helped work on it.
Granted, not a lot of it is my code, but I do think a new pair of eyes would be helpful 🙂)

**Comment by UtkarshKr007** [comment]
We might have to look at issue: #131 before solving the white screen problem.
I can consistently reproduce that issue by having the teacher pause and play the round before the student has given the camera permission. This will keep the screen white even after the permission has been granted.

These are the errors in the console: 


Notably, the second error regarding 'parentNode of undefined' occurs after the what's supposed to be ar view has ended.

**Review by UtkarshKr007 — COMMENTED** [review]
Should we also delete the ar-view-component spec file since it's empty.

**Comment by floogulinc** [comment]
> We might have to look at issue: #131 before solving the white screen problem.
> I can consistently reproduce that issue by having the teacher pause and play the round before the student has given the camera permission. This will keep the screen white even after the permission has been granted.

Thanks for catching this, I'll take a look. I have been thinking of looking at using the new browser permissions APIs to try and request perms as soon as the session starts (at least on supported browsers, aka not Safari). I might try and do that in this PR.

**Comment by floogulinc** [comment]
@UtkarshKr007 In my testing what I see happen in that case is as long as the student did hit the allow button, it will work after another pause/play cycle.

**Comment by floogulinc** [comment]
After more experimentation, truly fixing the permissions issues is going to be a major thing so I'm reopening this for review.

**Review by UtkarshKr007 — APPROVED** [review]

**Review by UtkarshKr007 — APPROVED** [review]

**Review by kklamberty — APPROVED** [review]
@UtkarshKr007 I appreciate your comment about how to recreate the white screen issue. Thanks! I still do have that white screen issue, but the permissions for the camera on subsequent rounds do seem to stick once I've given them. I don't have an Android device to test that bug. Thanks for your work on this, Joe and Paul!

**Pull request merged**
