### PR TITLE
About Page

### PR DESCRIPTION
**Pull request by helloworld12321**

### CODE REVIEW

**Comment by helloworld12321** [comment]
In good news, it looks like GitHub doesn't mind if we use the little octocat silhouette next to a link, as long as we don't pretend that we're GitHub-affiliated or anything.

From <https://github.com/logos>:

> ### Do these awesome things
>
> &hellip;
> ✔️ Use the Mark in social buttons to link to your GitHub profile or project 
> &hellip;

**Review by audreylemeur — APPROVED** [review]

**Review by UtkarshKr007 — APPROVED** [review]
The about page looks really clean. Like the icons. All the links are clickable and lead to the right place.

**Pull request merged**
