### PR TITLE
Add feedback and animations for collecting pollen

### PR DESCRIPTION
**Pull request by floogulinc**

### CODE REVIEW

**Comment by floogulinc** [comment]
Here's a short screen recording of the animations in action:

https://user-images.githubusercontent.com/1300395/105741186-a1411300-5eff-11eb-9d5e-f99072dda70d.mp4

**Review by audreylemeur — CHANGES_REQUESTED** [review]
I don't know what exactly is wrong, but when I click create join code, it flashes the code for less than a second then the button reappears.

**Comment by floogulinc** [comment]
> I don't know what exactly is wrong, but when I click create join code, it flashes the code for less than a second then the button reappears.

@audreylemeur I'm not having this issue on the Vercel deployment. Are you running it locally with the Firebase emulator?

**Comment by helloworld12321** [comment]
@audreylemeur Oh, weird! Can I ask two more questions about that?

1. Do you get any errors in the browser console?
2. Would you be able to make a screen recording to show a) the circumstances under which you're finding this bug, and b) what the bug looks like when it happens?

Thanks very much for the bug report!

**Comment by audreylemeur** [comment]
> > I don't know what exactly is wrong, but when I click create join code, it flashes the code for less than a second then the button reappears.
> 
> @audreylemeur I'm not having this issue on the Vercel deployment. Are you running it locally with the Firebase emulator?
> 
> This may be caused by your computer's clock being incorrect, try making sure it's syncing with an NTP server.

Thanks Paul that's what the issue was. I've dual booted my computer and sometimes it doesn't sync the clock immediately when I switch os.

**Review by audreylemeur — COMMENTED** [review]
Maybe this was already discussed but did we want this text to be all lowercase:
image
The animation looks really good otherwise.

**Comment by floogulinc** [comment]
> Thanks Paul that's what the issue was. I've dual booted my computer and sometimes it doesn't sync the clock immediately when I switch os.

@audreylemeur Ah yes that totally makes sense since Linux by defaults expects the real-time clock to use UTC while Windows sets it to your local timezone. You can actually [set Windows to use UTC as well](https://wiki.archlinux.org/index.php/System_time#UTC_in_Windows) to prevent this issue from happening when you switch OSes.

By the way, was this happening when testing locally with the emulator or was it happening with the Vercel deployment?

**Comment by floogulinc** [comment]
> Maybe this was already discussed but did we want this text to be all lowercase:
> image

We have issue #217 open to address that.

**Review by audreylemeur — APPROVED** [review]

**Comment by audreylemeur** [comment]
> > Thanks Paul that's what the issue was. I've dual booted my computer and sometimes it doesn't sync the clock immediately when I switch os.
> 
> @audreylemeur Ah yes that totally makes sense since Linux by defaults expects the real-time clock to use UTC while Windows sets it to your local timezone. You can actually [set Windows to use UTC as well](https://wiki.archlinux.org/index.php/System_time#UTC_in_Windows) to prevent this issue from happening when you switch OSes.
> 
> By the way, was this happening when testing locally with the emulator or was it happening with the Vercel deployment?

Vercel deployment

**Review by kklamberty — APPROVED** [review]
These animations are very engaging! I think it looks great.

**Review by UtkarshKr007 — APPROVED** [review]
The animation for collection pollen looks great.

**Pull request merged**
