### PR TITLE
Run `npm audit fix` to update some vulnerable dependencies

### PR DESCRIPTION
**Pull request by floogulinc**
This will have the effect of closing #242 and #252.

### CODE REVIEW

**Comment by kklamberty** [comment]
Can you specify a little more about what you'd like for a person to try in order to help verify that these updates didn't break something? Any suggestions? Thanks!

**Comment by floogulinc** [comment]
@kklamberty There really isn't anything specific to try considering these are minor updates and all the tests pass.

**Review by UtkarshKr007 — APPROVED** [review]
Checked out the preview and didn't see any breaking change

**Review by helloworld12321 — APPROVED** [review]
Same here—looks all good, thanks! :)

**Pull request merged**
